# Generated by Django 5.0.4 on 2024-04-17 01:00

import blogapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloggerhandle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, unique=True)),
                ('Content', models.TextField()),
                ('blog_slug', models.SlugField(blank=True, unique=True)),
                ('Images', models.ImageField(upload_to=blogapp.models.user_blog_images)),
                ('Date_Uploaded', models.DateTimeField(auto_now_add=True)),
                ('last_Updated', models.DateTimeField(auto_now=True)),
                ('handle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bloggerhandle.bloghandle')),
            ],
        ),
        migrations.CreateModel(
            name='BlogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
