# Generated by Django 5.0.4 on 2024-04-17 02:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=accounts.models.user_profile_pics_directory),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
