# Generated by Django 5.0.4 on 2024-04-17 01:00

import bloggerhandle.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('banner', models.ImageField(upload_to=bloggerhandle.models.user_bloghandle_banner)),
                ('blogger', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
